spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/az2359066401/sc-one-search/
          search-paths: config-file
          username: 2359066401@qq.com
          password: az910719
      label: master
server:
  port: 8787
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka